#!/bin/bash
#
# Buildroot post-image script
# Runs after images are generated
# Creates the final bootable ISO with GRUB2
#

BINARIES_DIR="$1"
AINUX_ROOT="$(cd "$(dirname "$0")/../.." && pwd)"

echo "[ainux post-image] Generating bootable ISO..."

# The ISO is already generated by Buildroot's ISO9660 support
# This script just adds any final touches

if [ -f "${BINARIES_DIR}/rootfs.iso9660" ]; then
    echo "[ainux post-image] ISO generated: ${BINARIES_DIR}/rootfs.iso9660"
    echo "[ainux post-image] Size: $(du -h "${BINARIES_DIR}/rootfs.iso9660" | cut -f1)"
fi

echo "[ainux post-image] Done!"
